export const REQUEST_ENTRIES_ALL = "REQUEST_ENTRIES_ALL";
export const GET_ENTRIES_ALL_SUCCESS = "GET_ENTRIES_ALL_SUCCESS";
export const GET_ENTRIES_ALL_FAILURE = "GET_ENTRIES_ALL_FAILURE";

export const REQUEST_ENTRY_SINGLE = "REQUEST_ENTRY_SINGLE";
export const GET_ENTRY_SINGLE_SUCCESS = "GET_ENTRY_SINGLE_SUCCESS";
export const GET_ENTRY_SINGLE_FAILURE = "GET_ENTRY_SINGLE_FAILURE";
